version: 2.1

workflow:
  build-deploy:
    jobs:
      - build
      - test:
          override:
            - echo "done"

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run: node --version